"use client";

import { useState, useEffect } from "react";
import { useComparisonStore } from "@/store/useComparisonStore";
import { LOADING_FACTS } from "@/lib/loadingFacts";
import { ArrowRight, Renew, Information } from "@carbon/icons-react";
import { useSearchParams } from "next/navigation";

export function ComparativeAnalysisPanel() {
  const searchParams = useSearchParams();
  const comparisonId = searchParams.get("id");

  const {
    comparisonResult,
    comparisonLoading,
    comparisonError,
    generateComparisonAnalysis,
  } = useComparisonStore();

  const [loadingFactIndex, setLoadingFactIndex] = useState(0);

  const handleGenerate = async () => {
    if (!comparisonId) {
      return;
    }
    setLoadingFactIndex(Math.floor(Math.random() * LOADING_FACTS.length));
    await generateComparisonAnalysis(comparisonId);
  };

  useEffect(() => {
    if (comparisonLoading) {
      const interval = setInterval(() => {
        setLoadingFactIndex((prev) => (prev + 1) % LOADING_FACTS.length);
      }, 3000);
      return () => clearInterval(interval);
    }
  }, [comparisonLoading]);

  return (
    <div className="mt-8 border-t border-border-color pt-8">
      {!comparisonResult && !comparisonLoading && !comparisonError && (
        <div className="text-center">
          <div className="inline-flex items-start gap-3 p-4 border-l-2 border-accent max-w-md text-left">
            <Information size={20} className="text-accent mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm text-text-primary font-medium mb-1">
                AI-Powered Comparative Analysis
              </p>
              <p className="text-sm text-text-secondary font-serif">
                Generate an in-depth comparison analyzing differences in framing, bias, and perspective between these two articles.
              </p>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={comparisonLoading}
            className="mt-6 px-8 py-4 bg-accent hover:bg-accent-hover text-text-primary disabled:opacity-50 disabled:cursor-not-allowed font-semibold tracking-wide transition-colors flex items-center gap-3 text-lg mx-auto"
          >
            Generate Comparative Analysis
            <ArrowRight size={20} />
          </button>
        </div>
      )}

      {comparisonLoading && (
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-accent mb-4"></div>
          <p className="text-lg text-text-primary font-medium mb-2">
            Analyzing comparison...
          </p>
          <p className="text-sm text-text-secondary">
            {LOADING_FACTS[loadingFactIndex]}
          </p>
        </div>
      )}

      {comparisonError && (
        <div className="text-center py-8">
          <p className="text-sm text-danger mb-4">{comparisonError}</p>
          <button
            onClick={handleGenerate}
            className="px-6 py-3 border border-border-color hover:bg-bg-surface transition-colors text-sm font-medium inline-flex items-center gap-2"
          >
            <Renew size={16} />
            Try Again
          </button>
        </div>
      )}

      {comparisonResult && !comparisonLoading && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold text-text-primary">
              Comparative Analysis
            </h3>
            <span className="text-xs px-2 py-1 bg-bg-surface border border-border-color text-text-secondary italic">
              Previously generated
            </span>
          </div>

          <div className="prose prose-sm max-w-none">
            <div className="border-l-2 border-accent pl-6 py-4">
              <div className="text-sm leading-relaxed text-text-primary font-serif whitespace-pre-wrap">
                {comparisonResult}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-center gap-3 text-xs text-text-secondary">
            <Information size={16} />
            <span>
              This analysis was generated by AI and should be interpreted with discretion.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
