export const LOADING_FACTS = [
  "Media bias can appear in word choice, framing, and what stories are omitted entirely.",
  "A 2020 study found that headline framing alone can shift reader perception by up to 15%.",
  "Loaded language uses emotionally charged words to influence readers beyond the facts.",
  "Bias by omission — leaving out one side of a story — is one of the hardest forms to detect.",
  "The same event described with different verbs can imply very different levels of agency.",
  "Source selection bias occurs when outlets consistently quote only voices that support one view.",
  "Framing effects were first formally studied by Kahneman and Tversky in the early 1980s.",
  "Word connotation matters: 'protestors' vs 'rioters' describes the same event very differently.",
  "Confirmation bias leads readers to trust information that aligns with their existing beliefs.",
  "The 'overton window' describes the range of policies acceptable in mainstream discourse.",
  "Agenda-setting theory suggests media doesn't tell us what to think, but what to think about.",
  "Passive voice can obscure responsibility in political reporting ('mistakes were made').",
  "Cherry-picking data is a common technique to support a predetermined narrative.",
  "False balance occurs when outlets give equal weight to unequal evidence for 'fairness'.",
  "Semantic slanting uses euphemisms and dysphemisms to shape perception subtly.",
  "Studies show readers spend an average of just 15 seconds on news articles before scrolling.",
  "The first sentence of an article (the lede) often determines how readers interpret the rest.",
];
